### ISSUE TITLE
GHPages

### ISSUE THREAD

**Issue by linonetwo** [loveloki/slate-docs-cn#2]
能搞一个网站版的吗？

**Comment by Xheldon** [comment]
> 能搞一个网站版的吗？

根据这个文档生成的：https://slate.xheldon.com  @linonetwo  @loveloki

**Comment by loveloki** [comment]
抱歉最近没上github也没看邮箱

你可以试试 @Xheldon 生成的版本~

**Comment by linonetwo** [comment]
感觉蛮好的
